spring.application.name=Production

spring.datasource.url=jdbc:mysql://localhost:3306/prodb1a

spring.datasource.username=root

spring.datasource.password=testing

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect